### ISSUE TITLE
I can't compile

### ISSUE THREAD

**Issue by casanova-uja** [CedarvilleCS/CedarLogic#33]
Hi, 
I am trying to compile Cedar Logic but i am not getting it.
When I run ''mkdir build && cd build && cmake .. "Visual Studio 15 2017" it gives me an error since it can't find the "Visual Studio 15 2017" folder. 

Some help, please.

**Comment by casanova-uja** [comment]
You must run 'mkdir build && cd build && cmake ..' and then  "Visual Studio 15 2017" will be created.

**Comment by joe-sonrichard** [comment]
@casanova-uja, did you get it to compile? We've been having difficulties with that too - see #28

**Comment by casanova-uja** [comment]
Yes, I do,

I was using:

mkdir build && cd build && cmake .. "Visual Studio 15 2017"

must be

mkdir build && cd build && cmake ..

After that I can open the solution file in Visual Studio 2017 ant it
compile perfectly.
