### ISSUE TITLE
Add binary release to GitHub page

### ISSUE THREAD

**Issue by sellicott** [CedarvilleCS/CedarLogic#39]
Hi Joe!
I thought it would probably be good to add some binary releases of cedarlogic to the project so people don't need to compile from source to get the latest version. It would be really neat if it was done with CI (I haven't been brave enough to try that with any of my projects yet).
Thanks,
-Sam Ellicott
Soli Deo Gloria

**Comment by kshomper** [comment]
Reviewed.

**Comment by JoeHCQ1** [comment]
@kshomper thanks! Just published a release with the binary installer: https://github.com/CedarvilleCS/CedarLogic/releases/tag/v2.3.6
